apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
